#!/bin/bash

DATE=`date "+%Y_%m_%d"`
VERSION=`git tag | tail -n 1`

all: build-release

run:
	npm run dev

format:
	npm run format

build-release:
	@echo "todo"

download-dependence:
	npm install

clean:
	@echo "todo"
