package config

import (
	"log"
	"os"
)

const cert string = `-----BEGIN CERTIFICATE-----
MIIEIjCCAoqgAwIBAgIRAPp5+hZOFZH4m75MerGAQYIwDQYJKoZIhvcNAQELBQAw
XTEeMBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMRkwFwYDVQQLDBBibHVl
QGJsdWUtbGFwdG9wMSAwHgYDVQQDDBdta2NlcnQgYmx1ZUBibHVlLWxhcHRvcDAe
Fw0yMzAzMDcxMTU5NDNaFw0yNTA2MDcxMTU5NDNaMEQxJzAlBgNVBAoTHm1rY2Vy
dCBkZXZlbG9wbWVudCBjZXJ0aWZpY2F0ZTEZMBcGA1UECwwQYmx1ZUBibHVlLWxh
cHRvcDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMxa2KVNeekJM+pk
rX7ocxcq3MSmFghmD9oFg+fHP4ufU8nujU2tWpIZjVOTRjT5Xk/UNjzbrlKdXjVl
eFP2jKNn8ZgiFUVQMYDC+GizKCoMZP0t1KA0Qog/2lLYN6xAtTtADRoaQKmj6zJg
ECzbTKBqpi/HFFJVqjobx8x1xN3tSXRkYqGeWblCbKNUt0AaysTUC87txoE3Sedd
C5Sb1QDgIJvG8mytct5pRl+pwIW1kUiZ+mg/RD7qmqEyQNmfk48A0HgtQ/mlyeXH
/C0isjrKAYy9zr1OvUO9bF+VJvfBJO4GsoHnwhEb00otOkbMnwvsjuSIllibnULc
BUiALbUCAwEAAaN2MHQwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUF
BwMBMB8GA1UdIwQYMBaAFCnPgdcOjw0yPFTlHTFmS6NfcybqMCwGA1UdEQQlMCOC
CWxvY2FsaG9zdIcEfwAAAYcQAAAAAAAAAAAAAAAAAAAAATANBgkqhkiG9w0BAQsF
AAOCAYEAZ36yVmm3pRkM2hwu0YaAZFEOXuh8CjT7pFrNKvNQky6aRVO8eFtCnhOL
qTQExKOxILoygBn8RYzD5/euZPjPVh+fQX3e6wFhkXCJy/zVjpEwyXicXuBCyB4d
DmDYAqIPKtb/W8JYYabEOJWWpCz0J2w/Dtnh4RfjwttY2DTAB+xAtJhqorj0epHV
hXw5TG2ZWPVIR//SD6a7Dj1Rv72PWF+T9miCiN/cvioQiDTXvn2sbS25AXX3M5ba
NVP/J7GvJI1VOvKgEq3iB8lnMk5OESD+t4oL2lpOoUJxeHacnB2MtcIpf2GPA+E4
knjs6/2zEnFX2fE99jjvML4v1iYIlvCuz1ENNQ/A8YrKk7Ldhx1YBWVvEdCa0ryw
oKJlJgaWTVEoew9dOvk9zk72Xkx1NC2s8qQ3uB27VpShhoDELvy8h71jBGsTMzpD
3mqaTaVnYj1t5oMwmc6PVo5RHHS0j8Lx3FsPqyle1X7r394igSIYUZpRXnagnwWp
y8qPjUm3
-----END CERTIFICATE-----`

func saveDefaultCert() {
	if _, err := os.Stat(CertFile); err != nil {
		if os.IsNotExist(err) {
			if err := os.WriteFile(CertFile, []byte(cert), 0666); err != nil {
				log.Fatalln(err)
			}
		}
	}
}
